[tool.poetry]
name = "pjecz-citas-v2-cliente-api-oauth2"
version = "2.1.0"
description = "API OAuth2 del Sistema de Citas hecho con FastAPI"
authors = ["Guillermo Valdes <guillermo.valdes@pjecz.gob.mx>"]
license = "AGPL3"
readme = "README.md"
packages = [{include = "pjecz_citas_v2_cliente_api_oauth2"}]

[tool.poetry.dependencies]
python = "^3.10"
python-dotenv = "^0.21.0"
fastapi = "^0.89.1"
fastapi-pagination = {extras = ["sqlalchemy"], version = "^0.11.2"}
gunicorn = "^20.1.0"
uvicorn = "^0.20.0"
hashids = "^1.3.1"
nest-asyncio = "^1.5.6"
pydantic = "^1.10.4"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
sqlalchemy = "^1.4.46"
sqlalchemy-utils = "^0.39.0"
unidecode = "^1.3.6"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
pytz = "^2022.7.1"
psycopg2-binary = "^2.9.5"
redis = "^4.4.2"
rq = "^1.12.0"
python-multipart = "^0.0.5"


[tool.poetry.group.dev.dependencies]
pylint = "^2.15.10"
black = "^22.12.0"
pylint-sqlalchemy = "^0.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 256
